Q. Declare a float value and store it in a variable.
Check the type and print the id of the same.

In [43]:
a = 10.5
print ('type of varaible:' ,type(a), a)
print ('ID of variable:',id(a))

type of varaible: <class 'float'> 10.5
ID of variable: 521676624496


Q. Arithmetic Operations on float
Take two different float values.
Store them in two different variables.
Do below operations on them:-
 Find sum of both numbers
 Find difference between them
 Find the product of both numbers.
 Find value after dividing first num with second number
 Find the remainder after dividing first number with second number
 Find the quotient after dividing first number with second number
 Find the result of the first num to the power of the second number.

In [41]:
a=10.5
b=20.6

print('Find sum of both numbers:' , a+b ) 
print('Find difference between them:', a-b)
print('Find the product of both numbers:', a*b)
print('Find value after dividing first num with second number:', a/b)
print('Find the reminder after dividing first number with second number:', a%b)
print('Find the quotient after dividing first number with second number:', a//b)
print('Find the result of the first num to the power of the second number:', a**b)



Find sum of both numbers: 31.1
Find difference between them: -10.100000000000001
Find the product of both numbers: 216.3
Find value after dividing first num with second number: 0.5097087378640777
Find the reminder after dividing first number with second number: 10.5
Find the quotient after dividing first number with second number: 0.0
Find the result of the first num to the power of the second number: 1.0876760377706958e+21


Q. Comparison Operators on float
Take two different float values.
Store them in two different variables.

Do below operations on them:-

Compare these two numbers with below operator:-

Greater than, '>'

Smaller than, '<'

Greater than or equal to, '>='

Less than or equal to, '<='

observe their output(return type should be boolean)


In [44]:
a=10.5
b=20.8
print ('Greater than:', a>b)
print ('Smaller than:', a<b)
print ('Greaterthan or requal to:',a>=b)
print ('Lessthan or requal to:',a<=b)

Greater than: False
Smaller than: True
Greaterthan or requal to: False
Lessthan or requal to: True


Q.Equality Operator
Take two different float values.
Store them in two different variables.
Equate them using equality operators (==, !=)
Observe the output(return type should be boolean)


In [16]:
a=100.2
b=200.9
print(a==b)
print(a!=b)

False
True


In [46]:
# Q. Logical operators
# Observe the output of below code
# Cross check the output manually

print(10.20 and 20.30) #both are true and second value taken Output is 20.3  
## Correct, Because in 'And' operator If A is true then result will be B

print(0.0 and 20.30) #First is false so first value taken->Output is 0.0
## Correct, Because in 'And' operator If A is false then result will be A

print(20.30 and 0.0) #Goes to till second and second value is false so second is taken>Output is 0.0
## Correct, Because in 'And' operator If A is true then result will be B

print(0.0 and 0.0) #First is false so first value is taken->Output is 0.0
## Correct, Because in 'And' operator If A is false then result will be A

print(10.20 or 20.30) #First is True so first value is taken>Output is 10.2
## Correct, Because in 'OR' operator If A is true then result will be A

print(0.0 or 20.30) #Goes to till second and second is true second value is taken->Output is 20.3
## Correct, Because in 'OR' operator If A is false then result will be B

print(20.30 or 0.0) #First is True so first value is taken->Output is 20.3
## Correct, Because in 'OR' operator If A is true then result will be A

print(0.0 or 0.0) #Goes to till second and second is also false and second value is taken>Output is 0.0
## Correct, Because in 'OR' operator If A is true then result will be A

print(not 10.20) #-Not of true is false->Output is False
## Correct, Because any value is true apart from 0

print(not 0.0) #Not of false is True>Output is True
## Correct, Because zero is false

20.3
0.0
0.0
0.0
10.2
20.3
20.3
0.0
False
True


Q. What is the output of expression inside print statement. Cross check
before running the program.
a = 10.20
b - 10.20
print(a is b) #True or False? True 10.20<256
print(a is not b) #True or False? False
Why the Id of float values are different when the same value is
assigned to two different variables
ex: a = 10.5 b=10.5. but id will be same if I assign the variable
having float i.e. a=c then both a and c's Id are same

### print (a is b), output will be false
### print (a is not b), output will be true
### Because we dont have object resuability concept in float. because infinity numbers will be there in between 1.0 to 2.0.  


In [32]:
a=10.20
b=10.20
print (a is b)
print (a is not b)

False
True


Q. Bitwise operation is not applicable between instances of float.
Why the Id of float values are different when the same value is
assigned to two different variables
ex: a = 10.5 b=10.5. but id will be same if I assign the variable
having float i.e. a=c then both a and c's Id are same
Object reusability concept is not applicable on float values.

### We have rule in object resualibility concept that, integer values from -5 to 256 in between that only object reusalibity concept will work and it will re-use the address in heap area. 
### Float values cannot be resued because infinity numbers will be there in between 1.0 to 2.0.  

In [45]:
# Q. Membership operation
# in, not in are two membership operators and it returns boolean value
print('2.7' in 'Python2.7.8') #True, because 2.7 is available in given string
print(10.20 in [10,10.20,10+20j,'Python']) #True,because 10.20 is available in given data
print(10.20 in (10,10.20,10+20j,'Python')) # True, because 10.20 is available in given data
print(20.30 in {1,20.30,30+40j}) # True,because 20.30 is available in given data
print(2.3 in {1:100, 2.3:200, 30+40j:300}) # True, because 2.3 is available in given data
print(10 in range(20)) # True, because 10 is in the range of 0-20

True
True
True
True
True
True
